image: openjdk:17-oracle

stages:
  - build
  - deploy


variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

before_script:
  - apt-get update -qy
  - apt-get install -y maven

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

deploy:
  stage: deploy
  script:
    - echo "Deploying to web server"
    # Add your deployment script here
