name: List services in GCP
on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
         token_format: 'access_token'
         workload_identity_provider: ${{ secrets.WORKLOAD_PROVIDER_ID }}
         service_account: ${{secrets.SECRET_SERVICES}}
    - id: 'gcloud'
      name: List Instances
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
