name: Prepare Manifests and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1-c
  ENVIRONMENT: dev

jobs:
  setup-prepare-manifests-deploy:
    name: Setup, Prepare, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/209363497979/locations/global/workloadIdentityPools/github-wif-pool/providers/github-wif-pool-provider'
        service_account: 'github-account-wfi@github-gcs-workload.iam.gserviceaccount.com'
