name: Prepare Manifests and Deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1-c
  ENVIRONMENT: dev

jobs:
  setup-prepare-manifests-deploy:
    name: Setup, Prepare, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        #token_format: 'access_token'
        workload_identity_provider: 'projects/568856489713/locations/global/workloadIdentityPools/pool-workload/providers/pool-workload-provider'
        service_account: 'services-account@my-project-wif.iam.gserviceaccount.com'
